### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4927: character maps to <undefined>

### ISSUE THREAD

**Issue by andymule** [SmartArduino/Doiting_BL#6]
Trying to flash anything and I get this error

========= eflash loader config =========
=========c:\source\doiting_bl\bl_iot_sdk\tools\flash_tool\bl602\device_tree/bl_factory_params_iotkita_40m.dtsbl602/device_tree/ro_params.dtb=========
Traceback (most recent call last):
  File "core\bflb_simple_flasher.py", line 814, in flasher_download_thread
  File "core\bflb_simple_flasher.py", line 736, in flasher_download_cfg_ini_gen
  File "core\bflb_simple_flasher.py", line 543, in bl60x_mfg_flasher_eflash_loader_cfg
  File "lib\bflb_ro_params_device_tree.py", line 29, in bl_ro_params_device_tree
  File "lib\bflb_ro_params_device_tree.py", line 17, in bl_dts2dtb
  File "C:\Python37-32\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4927: character maps to <undefined>

![image](https://user-images.githubusercontent.com/1566594/108588651-2a851300-730f-11eb-8318-febe77fa99f9.png)

**Comment by edeavila** [comment]
same problem

**Comment by aryehassbian** [comment]
same here - tried several times and getting the issue while ONLY using the helloworld first.
Please assist.
